// Farmer Portraits Sync - swaps the farmer's outfit to match the portrait.
//
// This file is fixed: it ships as-is and never needs regenerating. The tag ->
// outfit-slot table it works from is generated by the portrait tool and travels
// with the artwork, in FarmerPortraitsExample\gml\FarmerPortraitsSlots.gml,
// which sets global.__sage_fps_table. That split is the whole install story:
// install this mod once, and re-export art as often as you like.

#macro SAGE_FPS_ID "sage_farmer_portraits_sync"

function __sage_fps_runtime() {
    if (global[$ "__sage_fps"] == undefined) {
        global.__sage_fps = {
            registered: undefined,
            pending:    true,        // dress the farmer once, as soon as one exists
            menu:       undefined,   // textbox instance, for the conversation edge
            warned:     undefined,   // last missing slot logged, so it logs once
            told:       undefined,   // has the missing-table warning been logged
            seen:       false,       // has the fingerprint below been taken yet
            season:     undefined,
            day:        undefined,
            dom:        undefined,
            weather:    undefined,
            loc:        undefined,
        };
    }
    return global.__sage_fps;
}

/// The generated table, or undefined if the artwork half is not installed.
/// Read fresh rather than cached: the file that defines it is a separate mod and
/// there is no ordering guarantee between the two at load time.
function __sage_fps_table() {
    var _t = global[$ "__sage_fps_table"];
    if (is_struct(_t)) return _t;
    var _rt = __sage_fps_runtime();
    if (_rt.told == undefined) {
        _rt.told = true;
        mmapi_log_warn(SAGE_FPS_ID,
            "no portrait table found - export your portraits from the tool and "
            + "install the FarmerPortraitsExample folder alongside this mod");
    }
    return undefined;
}

/// True when any input the portrait lookup reads has changed since last frame.
///
/// This is the whole efficiency story. Comparing five numbers costs nothing, so
/// the expensive part - building the context struct and up to nineteen key
/// strings - only runs on frames where the answer can actually differ. Every
/// field deulo_farmer_portraits_context() reads is covered: "inout" is derived
/// from the location and needs no entry of its own, and "cutscene" is deliberately
/// absent because cutscenes are never a moment to change clothes.
function __sage_fps_context_changed(_rt) {
    var _season = undefined, _day = undefined, _dom = undefined;
    if (is_struct(CALENDAR)) {
        _season = CALENDAR.season();
        _day    = CALENDAR.day_type();
        _dom    = CALENDAR.day();
    }
    var _weather = is_struct(WEATHER) ? WEATHER[$ "weather"] : undefined;
    var _loc = CURRENT_LOCATION_ID;

    if (_rt.seen
        && _rt.season == _season && _rt.day == _day && _rt.dom == _dom
        && _rt.weather == _weather && _rt.loc == _loc) return false;

    _rt.seen    = true;
    _rt.season  = _season;
    _rt.day     = _day;
    _rt.dom     = _dom;
    _rt.weather = _weather;
    _rt.loc     = _loc;
    return true;
}

/// True on the frame a conversation opens. The portrait becomes visible here, so
/// this is the one moment the clothes must agree with it even when nothing about
/// the world changed - the player may have cycled presets by hand since.
function __sage_fps_dialogue_started(_rt) {
    if (!is_struct(ANCHOR)) return false;
    var _menu = ANCHOR.get_menu(Menu.Textbox);
    if (_menu == _rt.menu) return false;
    _rt.menu = _menu;
    return _menu != undefined;
}

/// Is this a safe frame to rebuild the farmer's paper doll? When it is not the
/// change stays pending and is retried, so a season that turns while you sleep
/// still lands the moment you are back on your feet.
function __sage_fps_safe() {
    if (!instance_exists(obj_ari)) return false;
    if (!is_struct(ARI)) return false;
    // Sleeping, passing out, the end-of-day tally: the farmer is mid-sequence.
    if (ARI[$ "end_of_day_status"] != undefined) return false;
    // Cutscenes animate the farmer and route preset changes through the FSM, so
    // a swap mid-scene is the most likely thing to glitch.
    if (is_struct(MIST) && MIST.is_running()) return false;
    // The customization menu IS the wardrobe. Never fight the player inside it.
    if (is_struct(ANCHOR) && ANCHOR.get_menu(Menu.Customization) != undefined) return false;
    return true;
}

function __sage_fps_apply(_rt) {
    var _slots = __sage_fps_table();
    if (_slots == undefined) return;

    var _count = ARI.presets.count();
    if (_count <= 0) return;

    // Same key array, same order as the sprite lookup, so the first key with a
    // slot is the same key that won the portrait.
    var _keys = deulo_farmer_portraits_keys(deulo_farmer_portraits_context());
    for (var _i = 0; _i < array_length(_keys); _i++) {
        var _slot = _slots[$ _keys[_i]];
        if (_slot == undefined) continue;
        if (_slot < 0) return;
        if (_slot >= _count) {
            // A new farmer starts with ONE outfit preset, and presets can be
            // deleted, so a mapped slot may simply not exist. Leaving the
            // wardrobe alone beats dressing them in the wrong outfit - and this
            // log line is the only way to find that out from inside the game.
            if (_rt.warned != _slot) {
                _rt.warned = _slot;
                mmapi_log_warn(SAGE_FPS_ID, "portrait '" + _keys[_i]
                    + "' is mapped to outfit preset " + string(_slot + 1)
                    + ", but only " + string(_count)
                    + " exist - add presets in the customization menu");
            }
            return;
        }
        if (ARI.preset_index_selected == _slot) return;  // already right, skip the rebuild
        obj_ari.change_preset(_slot);
        return;
    }
}

/// Re-dress the farmer whenever the trigger that picks the portrait changes -
/// walking indoors, the weather turning, a new day, a new season - and again
/// whenever a conversation opens. In between the wardrobe is the player's:
/// cycling presets by hand sticks until the world moves on.
function sage_fps_tick() {
    var _rt = __sage_fps_runtime();
    try {
        if (__sage_fps_context_changed(_rt)) _rt.pending = true;
        if (__sage_fps_dialogue_started(_rt)) _rt.pending = true;
        if (!_rt.pending) return;
        if (!__sage_fps_safe()) return;   // still pending; try again next frame
        _rt.pending = false;
        __sage_fps_apply(_rt);
    } catch (_err) {
        // A wardrobe change is never worth taking the game down for.
        _rt.pending = false;
    }
}

function sage_fps_register() {
    var _rt = __sage_fps_runtime();
    if (_rt.registered != undefined) return;
    _rt.registered = true;
    mmapi_register(sage_fps_tick);
}

mmapi_mod_declare(SAGE_FPS_ID, "1.1.2");
sage_fps_register();
